sonar.projectKey=orgatick-server
sonar.organization=orgatick
sonar.projectName=Orgatick Server
sonar.projectVersion=1.0

sonar.sources=src
sonar.sourceEncoding=UTF-8

sonar.exclusions=\
**/*.test.ts,\
**/*.spec.ts,\
**/node_modules/**,\
**/dist/**,\
coverage/**

sonar.typescript.tsconfigPath=tsconfig.json
