sonar.projectKey=orgatick-server
sonar.projectName=Orgatick Server
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=tests

sonar.sourceEncoding=UTF-8

sonar.token=sqp_356fdbcd5edd304f4aeff08704be924b8df802dd

sonar.host.url=http://localhost:9000