sonar.projectKey=orgatick-server
sonar.projectName=Orgatick Server
sonar.projectVersion=1.0

# Source code
sonar.sources=src
sonar.sourceEncoding=UTF-8

# Test configuration
sonar.tests=tests
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts
sonar.exclusions=**/*.test.ts,**/*.spec.ts,**/node_modules/**,**/dist/**

# Coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# SonarQube server
sonar.host.url=http://localhost:9000
sonar.login=sqa_1f8a8027d5d71f91e9b50585c931132905d2a73c

# Analysis exclusions
sonar.cpd.exclusions=**/*test.ts,**/*.spec.ts
