export enum RegistrationStatus {
  DRAFT = 'DRAFT',
  APPROVAL_PENDING = 'APPROVAL_PENDING',
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  CONFIRMED = 'CONFIRMED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}
