export enum LedgerEntryType {
  DEBIT = 'DEBIT',
  CREDIT = 'CREDIT',
}

export enum LedgerCategory {
  EVENT_PAYMENT_HOLD = 'EVENT_PAYMENT_HOLD',
  EVENT_PAYMENT = 'EVENT_PAYMENT',
  EVENT_RELEASE = 'EVENT_RELEASE',
  EVENT_REFUND = 'EVENT_REFUND',
  REFUND = 'REFUND',
  PAYOUT = 'PAYOUT',
  PAYMENT_GATEWAY_FEE = 'PAYMENT_GATEWAY_FEE',
  PLATFORM_FEE = 'PLATFORM_FEE',
  TAX_DEDUCTION = 'TAX_DEDUCTION',
  SETTLEMENT_RELEASE = 'SETTLEMENT_RELEASE',
  PAYOUT_LOCK = 'PAYOUT_LOCK',
  PAYOUT_SUCCESS = 'PAYOUT_SUCCESS',
  PAYOUT_FAILED = 'PAYOUT_FAILED',
  ADJUSTMENT = 'ADJUSTMENT',
}

export enum LedgerBalanceType {
  HOLD = 'HOLD',
  AVAILABLE = 'AVAILABLE',
  LOCKED = 'LOCKED',
  WITHDRAWN = 'WITHDRAWN',
  REFUNDED = 'REFUNDED',
}

export enum LedgerReferenceType {
  PAYMENT = 'PAYMENT',
  REFUND = 'REFUND',
  PAYOUT = 'PAYOUT',
  SETTLEMENT = 'SETTLEMENT',
}
