export enum TicketErrorCode {
  TICKET_NOT_FOUND = 'TICKET_NOT_FOUND',
  TICKET_INACTIVE = 'TICKET_INACTIVE',
  SALE_NOT_STARTED = 'SALE_NOT_STARTED',
  SALE_ENDED = 'SALE_ENDED',
  TICKET_SOLD_OUT = 'TICKET_SOLD_OUT',
  INVALID_GROUP_SIZE = 'INVALID_GROUP_SIZE',
  INVALID_GROUP_SETTINGS = 'INVALID_GROUP_SETTINGS',
  INVALID_PARTICIPANT_COUNT = 'INVALID_PARTICIPANT_COUNT',
  INVALID_TICKET_CONFIGURATION = 'INVALID_TICKET_CONFIGURATION',
}
