info:
  name: Get Domains by Environment
  type: http
  seq: 4

http:
  method: GET
  url: "{{url}}/domains/env/:env"
  params:
    - name: env
      value: development
      type: path
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
